# Generated by Django 2.0.1 on 2020-03-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clustering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_chusks', models.IntegerField(default=1.0)),
                ('Max_iteration', models.IntegerField(default=1.0)),
                ('Intializer', models.CharField(choices=[('kmeans++', 'Kmeans++'), ('random', 'Random')], max_length=128)),
                ('n_init', models.IntegerField(default=10.0)),
                ('Algorithm', models.CharField(choices=[('auto', 'Auto'), ('full', 'Full'), ('elkan', 'Elkan')], default='auto', max_length=10)),
                ('Tolerance', models.IntegerField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='som',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Learning_rate', models.IntegerField(default=1.0)),
                ('Epochi', models.IntegerField(default=1.0)),
                ('standard_Deviation', models.CharField(max_length=250)),
                ('Som_map_column', models.IntegerField(default=1.0)),
                ('Som_map_rows', models.IntegerField(default=1.0)),
                ('set_of_choices', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('performance_pca', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_Swigy_Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(max_length=255, upload_to='picture/%Y/%m/%d/')),
                ('Learning_rate', models.IntegerField(default=1.0)),
                ('epochi_range', models.IntegerField(default=1.0)),
            ],
        ),
    ]
